### ISSUE TITLE
Can't Import Script

### ISSUE THREAD

**Issue by landry314** [SmartPack/ScriptManager#7]
When I choose import script and then find my script it says "Please select a file with a .sh extension." I can't open my file even when it is called 'Backup.sh'. No idea...

I am using Lineage OS 18.1 (Android 11) on a Pixel 3 and version 4.4 of ScriptManager.

**Comment by sunilpaulmathew** [comment]
Hi, 
Thanks for the report. Just to clarify, are you using the in-built file picker or a third party file manager to pick the script?

**Comment by landry314** [comment]
i have tried both. your built in file picker doesnt even see the file. the system one doesnt open the file. in my normal file manager it says the file type is 'application/x-sh'. it should see this.

**Comment by sunilpaulmathew** [comment]
> uilt in file picker doesnt

It is a know issue that my app has problems to get file path from some file manager apps. Can you try with a different file manager (e.g. Material Files)?

**Comment by landry314** [comment]
i have material files... but i dont understand what to try. opening the file? yes, i can edit it in material files.

**Comment by landry314** [comment]
this is likely due to a lack of read permissions for external storage for the app. probably linked to issue for saving files i just opened... #6

**Comment by landry314** [comment]
https://stackoverflow.com/questions/51374551/read-and-write-external-storage-permission-isnt-working#51374708

**Comment by sunilpaulmathew** [comment]
> this is likely due to a lack of read permissions for external storage for the app. probably linked to issue for saving files i just opened... #6

No, we have the necessary permissions. What you have to test is, try import a file via Material Files (You'll hopefully find an option to select file manager somewhere while importing). Probably
1. Select import
2. Switch to Material files from somewhere in the menu (I don't know how it looks like in your phone)
3. Proceed as usual

**Comment by landry314** [comment]
This crashes Script Manager... "Script Manager keeps stopping"

**Comment by sunilpaulmathew** [comment]
Okay, if possible, try to capture a log and send it to me. I'll later test the app in android 11 emulator

**Comment by landry314** [comment]
should i download an app for that? logcat or something?

**Comment by sunilpaulmathew** [comment]
That will be a good and convenient for you. E.g., an app like https://play.google.com/store/apps/details?id=com.dp.logcatapp

**Comment by landry314** [comment]
i am using this app ^^ and i can filter smartpack.scriptmanager but that is a lot of lines. idk how to filter it further or find the relevant sections.

**Comment by sunilpaulmathew** [comment]
> i am using this app ^^ and i can filter smartpack.scriptmanager but that is a lot of lines. idk how to filter it further or find the relevant sections.

Make sure you capture at the time of the issue happened, & send it to me. Thanks

**Comment by landry314** [comment]
<<< log_count = 8 >>>
[01-27 04:05:27.959 1313:1356 D/ArtManagerInternalImpl]
/data/misc/iorapd/com.smartpack.scriptmanager/35/com.smartpack.scriptmanager.MainActivity/compiled_traces/compiled_trace.pb doesn't exist

[01-27 04:05:29.877 7869:7869 D/Documents]
shouldRestrictStorageAccessFramework = true, packageName = com.smartpack.scriptmanager

[01-27 04:05:48.338 32140:32140 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.smartpack.scriptmanager, PID: 32140
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://me.zhanghai.android.files.file_provider/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2Fscripts%2FBackup.sh flg=0x1 (has extras) }} to activity {com.smartpack.scriptmanager/com.smartpack.scriptmanager.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5009)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at b.c.a.k.j.h(:2)
	at com.smartpack.scriptmanager.MainActivity.onActivityResult(:4)
	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
	... 11 more

[01-27 04:05:48.362 1313:1688 W/ActivityTaskManager]
  Force finishing activity com.smartpack.scriptmanager/.MainActivity

[01-27 04:05:48.431 1313:4707 I/ActivityManager]
Process com.smartpack.scriptmanager (pid 32140) has died: prcp TOP 

[01-27 04:05:48.431 1313:1333 I/WindowManager]
WIN DEATH: Window{e791ea1 u0 com.smartpack.scriptmanager/com.smartpack.scriptmanager.MainActivity}

[01-27 04:05:48.433 1313:1333 W/InputDispatcher]
Attempted to unregister already unregistered input channel 'e791ea1 com.smartpack.scriptmanager/com.smartpack.scriptmanager.MainActivity (server)'

[01-27 04:05:48.863 1313:1343 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{de942fd u0 com.smartpack.scriptmanager/.MainActivity t-1 f}}

**Comment by sunilpaulmathew** [comment]
Hopefully fixed after the last commit.
